# Generated by Django 5.1.6 on 2025-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_status',
            field=models.CharField(choices=[('YURIDIK SHAXS', 'Yuridik shaxs'), ('JISMONIY SHAXS', 'Jismoniy shaxs')], editable=False, max_length=50),
        ),
    ]
