# Generated by Django 5.1.6 on 2025-02-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='../media/avatar/student/default-student.webp', upload_to='avatar/student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('student', 'Student'), ('admin', 'Administrator'), ('sponsor', 'Sponsor')], max_length=30, null=True),
        ),
    ]
