# Generated by Django 5.1.6 on 2025-02-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sponsor_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract_price',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
