# Generated by Django 5.1.6 on 2025-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sponsor_custom_amount_alter_sponsor_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='progress',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('MODERATSIYADA', 'Moderatsiyada'), ('TASDIQLANGAN', 'Tasdiqlangan'), ('BEKOR QILINGAN', 'Bekor qilingan')], max_length=30),
        ),
    ]
