# Generated by Django 5.1.6 on 2025-02-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sponsor_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.CharField(choices=[('1 MLN UZS', '1 000 000'), ('5 MLN UZS', '5 000 000'), ('7 MLN UZS', '7 000 000'), ('10 MLN UZS', '10 000 000'), ('30 MLN UZS', '30 000 000'), ('Boshqa', 'OTHERS')], max_length=30),
        ),
    ]
