# Generated by Django 5.1.6 on 2025-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sponsor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
