# Generated by Django 5.1.6 on 2025-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sponsor_custom_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='deposit_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
