# Generated by Django 5.1.6 on 2025-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sponsor_deposit_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
