# Generated by Django 5.1.6 on 2025-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_sponsor_custom_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.CharField(choices=[('1.000.000', '1 000 000'), ('5.000.000', '5 000 000'), ('7.000.000', '7 000 000'), ('10.000.000', '10 000 000'), ('30.000.000', '30 000 000'), ('Boshqa', 'OTHERS')], max_length=30),
        ),
    ]
