# Generated by Django 5.1.6 on 2025-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_phone_sponsor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
