# Generated by Django 5.1.6 on 2025-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='progress',
            field=models.CharField(choices=[('YANGI', 'Yangi'), ('Moderatsiyada', 'Moderatsiyada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], max_length=30),
        ),
    ]
