# Generated by Django 5.1.6 on 2025-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_sponsor_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='studentsponsor',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
