# Generated by Django 5.1.6 on 2025-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_contract_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allocated_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
