# Generated by Django 5.1.6 on 2025-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_student_allocated_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
