# Generated by Django 5.1.6 on 2025-02-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_totalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
